SELECT ?time ?coaches WHERE {
    ?service a TrainService;
        Destination Stabekk
        ArrivalTime ?time
        MakesUseOf ?train.
    ?train Coaches ?coaches.
}

SELECT ?time ?destination WHERE {
    ?service a TrainService;
        DepartureTime ?time
        Destintation ?destination
        origin Aas
    




}